### ISSUE TITLE
Example has some problems running

### ISSUE THREAD

**Issue by RepellantMold** [Clownacy/clownmdsdk#1]
![image](https://github.com/user-attachments/assets/7b313fa6-445d-49e9-b6ae-89535b848a81)

(output from standalone BlastEm [same result for RetroArch BlastEm], I'm able to play it if I spam continue in the debugger enough times, but resetting locks up the game)

https://github.com/user-attachments/assets/622046f3-0f88-47c4-a1e7-ebd47873bbc7

On RetroArch, Genesis Plus GX works but some colors have weird artifacts (???) and dies on resetting, Picodrive doesn't boot at all.

https://github.com/user-attachments/assets/ffeeef6c-972c-4aa3-9ebf-4f3dd18f627a

(tested on an NTSC Sega Genesis model 1 VA7 with a Mega Everdrive X5)

**Comment by Clownacy** [comment]
Thanks for reporting this. I should have thought to check my emulator's debug log while testing this... it's been trying to tell me this the whole time!

![image](https://github.com/user-attachments/assets/1495f5ba-9f1c-4c23-ae12-390aef99f96b)

What's going on is that the DMA fill was not being waited on properly, which is why you see that 'artifacting' in the colours: the DMA fill was being cut short.
